### ISSUE TITLE
test issue comments

### ISSUE THREAD

**Issue by shuperry** [shupeipei/graphql-demo#1]

**Comment by shuperry** [comment]
> @luckydrq I know the way you said, ctx.cookies.set('jwt', null)

thks, I know that now.

**Comment by luckydrq** [comment]
uh.. i've got a notification..haha

**Comment by shuperry** [comment]
@luckydrq uh, I want to see how to use quote, don't realized this also send email to author, haha.

**Comment by luckydrq** [comment]
It's ok :)
